### ISSUE TITLE
Feature Request: Age Range

### ISSUE THREAD

**Issue by hspinks** [simi/omniauth-facebook#147]
Love this gem, has worked well without any issue for me. One crucial piece of data that I wish it included, however, was the age range of the user.

According to [Facebook Developer docs](https://developers.facebook.com/docs/facebook-login/permissions/#optimizing) (see the 3rd bullet under Optimizing), "there is an age_range field included in the public profile for anyone who installs your app". However, the auth hash returned doesn't include this field as part of the data.

Would it be possible to include age_range in the response from Facebook?

**Comment by cjshort** [comment]
Am I doing this right? Here's my config in devise.rb:

  require "omniauth-facebook"
  config.omniauth :facebook, "APP KEY", "SECRET KEY", info_fields: "age_range"

and then in my user.rb model:

agerange: auth.info.age_range,

Can't seem to get it to work :(

**Comment by echezbro** [comment]
what data type did you save age-range as in your database?

**Comment by sdsunjay** [comment]
I am also not able to get the "age_range" either.

 config/initializers/devise.rb
`config.omniauth :facebook,"960469867376301","a77390f761f34b238558ae79ac43381a", scope: 'public_profile,email', info_fields: 'email, id,first_name,last_name,gender,picture,link,age_range'`

...
After much trial and error, I figured out how to get the age_rage. They **don't **make it easy.
`auth.extra.raw_info.age_range.min[1]`
 
@echezbro I have `age_min` as type integer in my schema.

Please check out my repo [https://github.com/sdsunjay/test-facebook-rails-app](https://github.com/sdsunjay/test-facebook-rails-app).
