### ISSUE TITLE
Support for New Facebook Login and Versioning

### ISSUE THREAD

**Issue by tuckerd** [simi/omniauth-facebook#152]
As I am sure you are aware, Facebook has announced changes to their login flow, permissions, and introduced versioning.

For reference:
- https://developers.facebook.com/blog/post/2014/04/30/the-new-facebook-login/
- [Changlog](https://developers.facebook.com/docs/apps/changelog#v2_0_permissions)
- [Upgrade Guide](https://developers.facebook.com/docs/apps/upgrading)

In terms of updating this gem, what is needed to implement any changes to support v2.0 and versioning in general?  Is there a timeline for these updates?  

I am willing to help out in any way I can (testing, documentation, code reviews....)

Cheers

**Comment by prototype-hacker** [comment]
I wonder if anyone encouter this: my omniaith-facebook works fine on localhost:3000, after I upload to aws, then the auth become following:

#<OmniAuth::AuthHash credentials=#<OmniAuth::AuthHash expires=true expires_at=1441728836 token="CAAW7rcA4U0gBAGEQDfZB4hsGsIQmTzDZCzBvzZA13UMJA9CKngZAjSFk0pfLZAdVRqSqZBaZCBmzw2DVR4HBFGlRFEHcPhX6uhOcEtzWyHR0v2k2mPbKvN9JPHdzh8bdI3BqkHbfRO7Mj2loHROKHZBS7geAaGwsu83S0tYmPwK37CTIWVZB9KZAoxNdhy2XZCFtct2T3UX03jeEoIm4lBMBZC5s"> extra=#<OmniAuth::AuthHash raw_info="{\"id\":\"1609374965977746\",\"email\":\"mike.ko\\u0040afusion.com\",\"first_name\":\"Mike\",\"gender\":\"male\",\"last_name\":\"Aft\",\"link\":\"https:\\/\\/www.facebook.com\\/app_scoped_user_id\\/1609374965977746\\/\",\"locale\":\"en_US\",\"name\":\"Mike Aft\",\"timezone\":8,\"updated_time\":\"2013-12-06T06:35:36+0000\",\"verified\":false}"> info=#<OmniAuth::AuthHash::InfoHash email="email" first_name="first_name" image="https://graph.facebook.com/v2.0/id/picture?type=large" last_name="last_name" name="name" urls=#<OmniAuth::AuthHash Facebook="link"> verified="verified"> provider="facebook" uid="id">

weird info hash, uid is id ... first_name is first_name... all correct info are in raw_info,
don't know what causes this
