### ISSUE TITLE
NoAuthorizationCode error when manually passing signed_request

### ISSUE THREAD

**Issue by jmzbond** [simi/omniauth-facebook#165]
As described in these two places:
- http://stackoverflow.com/questions/12370056/omniauth-strategies-facebook-noauthorizationcodeerror-must-pass-either-a-code
- https://github.com/mkdynamic/omniauth-facebook/issues/110

I received the error `OmniAuth::Strategies::Facebook::NoAuthorizationCodeError (must pass either a`code`parameter or a signed request (via`signed_request`parameter or a`fbsr_XXX`cookie)):` so am manually passing a `signed_request` param, but the error is still present. 

This is the URL: `http://localhost:3000/auth/facebook/callback?signed_request=ASDF.JOUYOUY`

More context: 
- Server-side login works fine
- Client-side login using JS SDK works fine on Safari\* (have not tested in Firefox or IE or mobile non-Chrome), but not in Chrome, which is what this question is about (and majority of my users use Chrome so it's super important)
- Gem versions:
  ruby (2.1.2)
  rails (4.1.1)
  oauth (0.4.7)
  oauth2 (1.0.0)
  omniauth (1.2.2)
  omniauth-facebook (2.0.0)
  omniauth-oauth2 (1.2.0)
- This is for an app in development mode, where as the developer, I am definitely authorized to log in

Also have a hugely long SO question (http://stackoverflow.com/questions/25819058/facebook-noauthorizationerror-after-passing-signed-parameters-manually) where I detail what I've done to troubleshoot and the fact that I'm still stuck... just going to use server-side for now.

**Comment by osnysantos** [comment]
@simi the code from @cristiansorinel worked for you? In my case just in Chrome it doesnt worked, even with @cristiansorinel code. I used the code from the example as well: https://github.com/mkdynamic/omniauth-facebook/blob/master/example/app.rb#L24
