### ISSUE TITLE
Address Facebook Reconnect Vulnerability in Readme

### ISSUE THREAD

**Issue by dylnclrk** [simi/omniauth-facebook#187]
omniauth-facebook should address the Facebook "Reconnect" vulnerability in its readme. I suspect the repository will be getting a lot of traffic because of this, and should clear up any confusion about it being vulnerable. http://sakurity.com/blog/2015/03/05/RECONNECT.html 

I'm currently investigating the effects, and will make sure to contribute to the discussion.

**Comment by simi** [comment]
PR is welcomed here

**Comment by simi** [comment]
If I understand this well, you need to CSRF your connect actions?

**Comment by dylnclrk** [comment]
Hey @simi my apologies, I somehow did not get the notifications about your response. I addressed the issue in my world, but would be more than happy to provide a PR which prevents CSRFing of the connect actions if you think it would be worthwhile.

Thanks!

**Comment by mkdynamic** [comment]
@dylnclrk PR welcome.

**Comment by bogdanRada** [comment]
any updates on this? This is a security vulnerability and it passed 8 months since last comment in this thread.  I am really interested if this was fixed or are there any plans of fixing this in the near future? Any response would be much appreciated .

**Comment by mkdynamic** [comment]
Nothing new to add. The CRSF on Facebook sign-in/sign-out still exists AFAIK. The CSRF potential for the `/auth/facebook` request step is a side-effect of the design of OmniAuth -- changing that endpoint to require CSRF protection I think is not viable without making this gem behave in a way that deviates from the OmniAuth "spec". We could add as an option (POST + CSRF token) but I don't think we can enable it by default. We should def. add info in the README about this. PRs on both welcome @bogdanRada
