### ISSUE TITLE
Scope doesn't seem to be working in omniauth.rb

### ISSUE THREAD

**Issue by mohaazeem** [simi/omniauth-facebook#249]
In my **omniauth.rb** file I pass a scope in the hash with some permissions that I would like my app to have access to. However, whenever someone tries to authenticate my app, they are only asked for the public profile and user friends permissions which are the default scopes. Does anyone have any idea why this could be happening?

Here's the file:

**config/initializers/omniauth.rb**

``` ruby
OmniAuth.config.logger = Rails.logger

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook, 'app_id', 'app_secret', scope: 'public_profile,user_location,user_friends,user_relationships',  info_fields: 'id,name,location,relationship_status,gender,friends,significant_other', display: 'popup'
end
```

I have tested things like messing up with the string, for example, by changing _gender_ to _gendre_, and the app crashes. So it actually recognizes the string when the scopes are valid but for some reason it doesn't ask the user for the permissions. Do I have to do something extra in the app settings on the Facebook Developers page?

Thanks

**Comment by chkelly** [comment]
I ran into something similiar. Got it working with the below:

```
Rails.application.config.middleware.use OmniAuth::Builder do
    provider :facebook, ENV['FACEBOOK_APP_ID'], ENV['FACEBOOK_APP_SECRET'],
           :scope => 'manage_pages,publish_pages',
           :client_options => {
		           :site => 'https://graph.facebook.com/v2.6',
		           :authorize_url => "https://www.facebook.com/v2.6/dialog/oauth"
           },
           token_params: { parse: :json }
end
```

**Comment by mohaazeem** [comment]
Thanks for the reply @chkelly. Unfortunately your solution didn't work with me.

I guess Facebook has a new policy now for requesting user permissions. If you navigate to **App Review** tab on your application's settings on Facebook's Developers page, you'll find that they now ask you to submit some stuff for review if you want to request a certain permission from the user. Stuff like how the user can see your usage of the permission, screencasts, Privacy Policy URL and other things of the sort, and you wait after that for their approval. I'm not certain if that's a must now and I can't find a workaround.

**Comment by chkelly** [comment]
Correct you do need to go through approval, you should be able to whitelist specific people though as testers (in your app settings) which will allow it to work (it does give them a warning about the app not being approved) but obviously that should be fine for development.

**Comment by mohaazeem** [comment]
@chkelly Yeah I guess that should work, but we wanted it to work with public users. I'll see if we can look into the approval thing. Thank you so much for your help!
