### ISSUE TITLE
Auth hash and public

### ISSUE THREAD

**Issue by chussenot** [simi/omniauth-facebook#250]
Hi there, 

We use the gem with Devise,

**config/initializers/devise.rb**

```
259   config.omniauth :facebook,
260     Gaston.providers.facebook.app_id, Gaston.providers.facebook.secret_id,
261     scope: 'email, public_profile, user_birthday, user_location',
262     image_size: :large
```

And the omniauth.auth response doesn't contain core fields `first_name` and `last_name`

**Pry breakpoint**

``` bash
[1] pry(#<Users::OmniauthCallbacksController>)> request.env['omniauth.auth']
=> {"provider"=>"facebook",
 "uid"=>"10152710252119",
 "info"=>
  {"email"=>"xxxx@xxxx.com",
   "name"=>"xxxxxx",
   "image"=>"http://graph.facebook.com/v2.6/1015237025521219/picture?type=large"},
 "credentials"=>
  {"token"=>
    "EAANSvg7Y1BsBAIefFb9YiNGHbPJIn0z1S2ZB7JMeHzDL5sr7HfbNGgCB0kC9UG5vxHwxhvdfzlGZCcwVtboi38qqvpE3S2p1ggQgRkxAkmTZAZA8waY4rKgjGOXYZBIs2TquR9vZBSKg14GC7eoT1RgpvYns7gZD",
   "expires_at"=>147540258,
   "expires"=>true},
 "extra"=>
  {"raw_info"=>
    {"name"=>"xxxx", "email"=>"xxxx@xxxx.com", "id"=>"101523102551219"}}}
```

**Gemfile**

```
 group :auth do
    gem 'devise',                   '~> 4.2'
    gem 'devise-i18n'               # Only yaml files
    gem 'omniauth',                 '~> 1.3'
    gem 'omniauth-facebook',        '~> 4.0'
    gem 'linkedin'
    gem 'omniauth-linkedin-oauth2', branch: 'master'
    gem 'omniauth-oauth',           '1.1'
    gem 'omniauth-oauth2',          '=1.2'
 end
```

**Comment by chussenot** [comment]
Do you know more about this issue ?

**Comment by tmac** [comment]
@chussenot Facebook, as of API 2.4, now requires you specify the fields you want.

http://stackoverflow.com/questions/31692355/facebook-only-returning-name-and-id-of-user

In omniauth you specify the info_fields like so:

  config.omniauth :facebook, FACEBOOK[:app_id], FACEBOOK[:app_secret],
    info_fields: 'first_name,last_name,email',
    scope:       'public_profile,email',
    image_size:  'large',
    client_options: {
      site:          'https://graph.facebook.com/v2.6',
      authorize_url: 'https://www.facebook.com/v2.6/dialog/oauth'
    }

Hope that helps.

**Comment by tjankov** [comment]
I'm still not getting those fields
