### ISSUE TITLE
Add more descriptive error for an invalid input field

### ISSUE THREAD

**Issue by AlexVPopov** [simi/omniauth-facebook#255]
I am using `omniauth-facebook` with `devise` and Rails 4.2. In `devise.rb`, if you have the following configuration:

``` ruby
config.omniauth :facebook,
                ENV['APP_ID'],
                ENV['APP_SECRET'],
                scope: 'email',
                info_fields: 'id,email,first_name,last_name,name,food'
```

and you add an invalid input field, which is not present in [this list](https://developers.facebook.com/docs/graph-api/reference/user/), then the flash that is displayed is:

> Could not authenticate you from Facebook because "Invalid credentials".

The relevant log line is:

> ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, {"message"=>"(#100) Tried accessing nonexisting field (food) on node type (User)", "type"=>"OAuthException", "code"=>100, "fbtrace_id"=>"Danam9owgDY"}: 
> {"error":{"message":"(#100) Tried accessing nonexisting field (food) on node type (User)","type":"OAuthException","code":100,"fbtrace_id":"Danam9owgDY"}}

I think there should be a more descriptive message, stating what the problem might be. If this issue is not relevant to `omniauth-facebook`, could you point me to which project `omniauth` or `devise` this would be relevant. Also, if you can point out the relevant code, that handles failures, that'd be great.

**Comment by simi** [comment]
The origin of this is in https://github.com/intridea/omniauth-oauth2/blob/464fcef6c0a5f1a7526b9701cec37f342ce57ae3/lib/omniauth/strategies/oauth2.rb#L77.

Not sure if we should handle this on our own here in omniauth-facebook or improve original omniauth-oauth2 code.

**Comment by AlexVPopov** [comment]
On the one hand, this is something Facebook specific and the exact error must be inferred from the error message. However, the code in omniauth-oauth2 implies that all `OAuth2::Error`s are caused by invalid credentials. I guess both pleases deserve improvement...
