### ISSUE TITLE
Not receiving email despite requesting it in scope/info_fields

### ISSUE THREAD

**Issue by jbaugh** [simi/omniauth-facebook#257]
See config below:
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook, AppConfig.get("facebook_application_id"), AppConfig.get("facebook_application_secret_key"),
            scope: "email,public_profile",
            info_fields: "name,first_name,last_name,email",
            provider_ignores_state: true,
            secure_image_url: true,
            image_size: :large,
            display: "popup"
            
end
```

When it asks for permission, it says the app is requesting the public profile. If I leave the entire scope through display hash blank (i.e. use the defaults), I still do not get email back.

The info hash in auth response is
`
#<OmniAuth::AuthHash::InfoHash first_name="..SNIPPED.." image="..SNIPPED.." last_name="..SNIPPED.." name="..SNIPPED..">
`

All the "solutions" I've found, don't seem to work. I am using omniauth 1.3.1 and omniauth-facebook 4.0.0. I am not using devise.

**Comment by gordysc** [comment]
FWIW I got this to work with the following with devise:
config.omniauth :facebook, ENV["FACEBOOK_APP_KEY"], ENV["FACEBOOK_APP_SECRET"], scope: 'email', fields: 'public_profile,email'

Also, I noticed my browser was holding onto a previous session pretty aggressively.  Clearing my cookies resolved it.  Hope this helps!

**Comment by gordysc** [comment]
For those who stumble on this issue, this is currently a known bug:
https://developers.facebook.com/bugs/1604634122901104/
