### ISSUE TITLE
Requested info fields not being returned

### ISSUE THREAD

**Issue by mradzwilla** [simi/omniauth-facebook#263]
Hey everybody. I made a StackOverflow post about the issue I was having: http://stackoverflow.com/questions/41081549/facebook-omniauth-hash-not-returning-info-fields

When I added other fields in (such as birthdays and things), the Facebook redirect did ask me to confirm that I was sharing that information. However, the requested info_fields do not show up in the response and I'm not sure what could be causing this issue.

**Comment by wonderphil** [comment]
+1 - http://stackoverflow.com/questions/41429793/omniauth-facebook-not-hash-not-containing-all-data

**Comment by jgrau** [comment]
I had the same issue today but then noticed that bundler had installed a very old version of `omniauth-facebook`. Running `bundle update omniauth-facebook` gave me the latest release. I believe it's also necessary to specify which info fields you need. Example from my app:

```
  provider(:facebook,
           ENV['FACEBOOK_APP_ID'],
           ENV['FACEBOOK_APP_SECRET'],
           scope: 'email,public_profile',
           info_fields: 'email,first_name,last_name,cover',
           image_size: 'large',
           client_options: {
             site: 'https://graph.facebook.com/v2.8',
             authorize_url: 'https://www.facebook.com/v2.8/dialog/oauth'
           })
```

I am not sure if the `client_options` is required - I use it to lock myself to an API version in the code.

**Comment by tdutreui** [comment]
Same thing here : scope and info_fields well populated but nothing returned except email and public profile infos.
The thing is that *your app need facebook preauthorization for being able to ask permissions for users* except email and public_profile. If the FB user is a developer of your app, your app does not need this preauthorization.
Source : https://developers.facebook.com/docs/facebook-login/review/how-to-submit
