### ISSUE TITLE
Gem Load Error is: private method `warn' called for nil:NilClass

### ISSUE THREAD

**Issue by neiman** [simi/omniauth-facebook#270]
Hashie looked like they just updated their logger class, which started to break this gem for me.

For a quick fix, I reverted the /hashie-3.5.2/lib/hashie/logger.rb to the previous code.

replacing their update
def self.logger
    @logger ||=
      if defined?(::Rails)
        Rails.logger
      else
        Logger.new(STDOUT)
      end
  end

back to 
def self.logger
    @logger ||= Logger.new(STDOUT)
end

Hope that helps somebody.

----------
Bundler::GemRequireError: There was an error while trying to load the gem 'omniauth-facebook'.
  Gem Load Error is: private method `warn' called for nil:NilClass
  Backtrace for gem load error is:
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:334:in `log_built_in_message'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:139:in `custom_writer'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:207:in `block in deep_update'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:200:in `each_pair'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:200:in `deep_update'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:115:in `initialize'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-1.4.1/lib/omniauth/auth_hash.rb:24:in `new'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-1.4.1/lib/omniauth/auth_hash.rb:24:in `regular_writer'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:140:in `custom_writer'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:207:in `block in deep_update'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:200:in `each_pair'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:200:in `deep_update'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:115:in `initialize'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-1.4.1/lib/omniauth.rb:45:in `new'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-1.4.1/lib/omniauth.rb:45:in `defaults'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-1.4.1/lib/omniauth.rb:50:in `initialize'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/singleton.rb:142:in `new'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/singleton.rb:142:in `block in instance'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/singleton.rb:140:in `synchronize'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/singleton.rb:140:in `instance'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-1.4.1/lib/omniauth.rb:119:in `config'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:127:in `<top (required)>'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-facebook-4.0.0/lib/omniauth/strategies/facebook.rb:1:in `<top (required)>'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-facebook-4.0.0/lib/omniauth/facebook.rb:2:in `<top (required)>'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-facebook-4.0.0/lib/omniauth-facebook.rb:1:in `<top (required)>'

**Comment by wbotelhos** [comment]
I fixed the `hashie` to version `3.5.1` and it worked.

**Comment by Fudoshiki** [comment]
same with hashie 3.5.2

**Comment by mrchenhao** [comment]
`hashie ` 3.5.2  is is also error
