### ISSUE TITLE
Error when authing on subdomain: Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected 

### ISSUE THREAD

**Issue by macmartine** [simi/omniauth-facebook#274]
I am trying to oauth on a wildcard subdomain. It works great then I use the top level domain, but when on subdomain I get:

Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected 

In the Facebook app I have http://lvh.me as the URL and lvh.me as the app domain.

Any ideas?

**Comment by bowekr** [comment]
same error here +1

**Comment by zerocool4u2** [comment]
try clearing your cookies for lvh.me and localhost on your browser, they might been colliding

**Comment by printercu** [comment]
Have faced same issue. Make sure you don't have `SameSite: Strict` setting for session cookie.

**Comment by Uriel7** [comment]
Same error +1
