### ISSUE TITLE
popup not work 

### ISSUE THREAD

**Issue by fbukevin** [simi/omniauth-facebook#275]
No matter I added `display: popup` in configs/initializers/omniauth.rb or appended `display=popup` in link href attribute like `<a href="/auth/facebook?display=popup">Test FB</a>`

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook, ENV['APP_ID'], ENV['APP_SECRET'],
      client_options: {
      site: 'https://graph.facebook.com/v2.8',
      authorize_url: "https://www.facebook.com/v2.8/dialog/oauth"
    },
  	scope: 'email,public_profile',
  	display: 'popup'
end
```

The screenshot is here:

<img width="1271" alt="1" src="https://cloud.githubusercontent.com/assets/4548874/24270284/7f2b33fc-104f-11e7-912e-8d475b575c79.png">

The message below: 
> You are using a display type of 'popup' in a large browser window or tab. For a better user experience, show this dialog with our JavaScript SDK without specifying an explicit display type. The SDK will choose the best display type for each environment. Alternatively, set height and width on your window.open() call to properly size this dialog if you have special requirements precluding you from using the SDK. This message is only visible to developers of your application.

**Comment by pensan** [comment]
Similar to #47 ?
