### ISSUE TITLE
Facebook not returning email for 1 app whereas returning for the other app for the same account.

### ISSUE THREAD

**Issue by mv27389** [simi/omniauth-facebook#280]
I'm using Facebook JavaScript SDK to login into admin. After login, I'm calling URL to fetch user details.
Following are the few details : 
1. Using 2 apps (same version 2.7), both for Web platform, with only change in their Valid OAuth redirect URIs.
2. Providing { scope: 'public_profile,email,publish_actions' } while logging in.
3. URL to fetch user details : https://graph.facebook.com/me?fields=id,name,email,birthday,age_range,gender,link,hometown,picture&locale=en_US
4. Using same account credentials while logging into both apps. 

For 1 app, while fetching user details, I'm getting email, whereas for the other app, email field in not coming. (For both apps, access token and user id is different)

Does anyone have any idea what is causing this behavior. What do I have do to fix this?

**Comment by islamaskar** [comment]
I have the same problem

**Comment by jonaselan** [comment]
The problem is the Facebook remove the field `email` from your [response](https://github.com/plataformatec/devise/wiki/OmniAuth%3A-Overview#facebook-returning-nulled-email). I am trying to make some workaround for that, but without success until now :/

**Comment by spagnolodesign** [comment]
Any update about it?
