### ISSUE TITLE
Authentication failure! invalid_credentials

### ISSUE THREAD

**Issue by filipesiciliano** [simi/omniauth-facebook#284]
ruby 2.1.0p0 
Rails 3.2.19
gem "omniauth-facebook", "~> 1.4"
gem "oauth2", "~> 0.8"

(facebook) Authentication failure! invalid_credentials: OAuth2::Error, : 
{"access_token":"EAAEZAmI4QnZCwBAB16r1dXA6bW18NyyIQ28BGbUO8C3nNZAq49G6MkdRr9wNw2hZAf9pIFEMRMTStTLe1THOLXTQWBcoTkqq9BvJLilHBacypCYjITSsdT2NdxJWdixBcw04AKofQdbT2pTyDjOZBJyAlIGXEAC1s2Mhw4uYkekttjrK30u1u","token_type":"bearer","expires_in":5181271}

**Comment by JulioOrellana** [comment]
same here, cannot make it work

![screen shot 2017-11-09 at 3 29 44 pm](https://user-images.githubusercontent.com/10372340/32622802-dddcd324-c562-11e7-916c-672bae4e9df0.png)

**Comment by Luna2442** [comment]
I have the same problem. Looked at all solutions and nothing helped.

**Comment by RTJ** [comment]
I'm having exactly the same problem ...
It was working before and since today I have this error.

**Comment by erkie** [comment]
The fix for this on my end was from this comment: https://github.com/mkdynamic/omniauth-facebook/pull/174#issuecomment-300299724

```ruby
provider :facebook, Rails.application.secrets.facebook_key, Rails.application.secrets.facebook_secret, {
  # From: https://github.com/mkdynamic/omniauth-facebook/pull/174#issuecomment-300299724
  # To fix: https://github.com/mkdynamic/omniauth-facebook/issues/284
  token_params: { parse: :json },
}
```

**Comment by yuvi17** [comment]
@filipesiciliano did @erkie 's comment help you out or you would need some more information?
This SO thread might be helpful: https://stackoverflow.com/questions/16176208/rails-could-not-authenticate-you-from-facebook-because-invalid-credentials
