### ISSUE TITLE
Rails Omniauth facebook not returning info fields other than default fields

### ISSUE THREAD

**Issue by vvsmanoharvadapalli** [simi/omniauth-facebook#302]
I'm using facebook authentication for my Rails 5 app. I want to fetch user details other than email. But it's not returning the specified fields. Here's my config for devise.rb

`config.omniauth :facebook, "APP ID", "APP Secret", scope: 'email', secure_image_url: true, :image_size => 'large', auth_type: 'https',info_fields: 'email,name,first_name,last_name,gender',
client_options: {
    site: "https://graph.facebook.com/v3.0",
    authorize_url: "https://www.facebook.com/v3.0/dialog/oauth"
    }`

I'm getting only email name and profile pic.
Please help me in this.

**Comment by alexeyshchepin** [comment]
Hi @vvsmanoharvadapalli! Have you found any solution? I got the same problem. The only difference is that I don't receive even an email :)
``ruby
callback_url: 'http://localhost:3000/users/auth/facebook/callback',
token_params: { parse: :json },
scope: 'email,public_profile',
secure_image_url: true,
image_size: 'large',
info_fields: 'email,first_name,last_name,picture,name'
```

```ruby
{"provider"=>"facebook",
 "uid"=>"11111111111111",
 "info"=>{"name"=>"Some Body", "image"=>"http://graph.facebook.com/11111111111111/picture?type=square"},
 "credentials"=>
  {"token"=>"TOKEN",
   "expires_at"=>1537473575,
   "expires"=>true},
 "extra"=>{"raw_info"=>{"name"=>"Some Body", "id"=>"11111111111111"}}}
```

**Comment by FarazPatankar** [comment]
I had a similar issue. I think it may be because by default, we are getting an older/different version of the gem. Explicitly writing `gem 'omniauth-facebook', '5.0.0'` in my `Gemfile` fixed it for me. Hopefully it'll work for you as well.

**Comment by alexeyshchepin** [comment]
@FarazPatankar Thanks a lot! It finally works ;)
