### ISSUE TITLE
Delay when processing callback in production

### ISSUE THREAD

**Issue by madgeekfiend** [simi/omniauth-facebook#31]
When I use omniauth facebook login in dev it works great fast and snappy. However, as soon as deploy to production running on Ubuntu and Nginx the callback takes forever to process. It works but takes a LONG time when I turn on debugging in rails 3.2.1 prod log it hangs here forever:

Started GET "/users/auth/facebook/callback?code=xxx" for 127.0.0.1 at 2012-03-01 21:50:48 -0800
Processing by Users::OmniauthCallbacksController#facebook as HTML

then after 1-5 seconds it process as normal. Only in production mode on Nginx. Any tips or suggestions where to look? It works just the login delay is too much. Rails 3.2.1, Nginx, Postgres, Devise 2, Omni 1.0.2, omni-fb 1.2

**Comment by Ajaxy** [comment]
I've suddenly ran into this bug after few months of successful running. Fortunately I found this issue and IPv6 tweak helped. But what could be the matter of a sudden change?

**Comment by ravuthlong** [comment]
@loureirorg you saved my life
