### ISSUE TITLE
Is this gem no longer maintained ?

### ISSUE THREAD

**Issue by bsh185** [simi/omniauth-facebook#327]
Facebook graph API is now at V4.0 and this gem current graph version is v2.10 and  will be deprecated on Nov 05, 2019 will there be any updates on this gem anytime soon ? is there an alternative to this gem ?

**Comment by simi** [comment]
You can use any version endpoint you need - https://github.com/mkdynamic/omniauth-facebook#api-version. If you'll be able to test V4.0 endpoint with this gem, we can release new version before 2.10 will be deprecated and move endpoint to some newer. We will need also to see differences to inform about backward incompatible changes.

Would you mind to help @bsh185?

**Comment by bsh185** [comment]
I tried both 3.0 and 4.0 and login via Facebook seems to work fine, i tried the V4.0 and my site was able to get the needed user info to create a new one (email, first name, last name) with no issues.

**Comment by svoop** [comment]
@simi Tested v4.0 with `scope: public_profile,email` and `info_fields: email,first_name,last_name` – works like a charm.

**Comment by edgar-abadines** [comment]
Is a new version coming out soon?  How can I help?

**Comment by simi** [comment]
We need to somehow decide which will be the new default version.

see also https://github.com/mkdynamic/omniauth-facebook/pull/329

**Comment by simi** [comment]
@svoop @bsh185 @edgar-abadines can you please test my cleanup of warnings before next release?

https://github.com/mkdynamic/omniauth-facebook/pull/331

**Comment by simi** [comment]
https://github.com/simi/omniauth-facebook/pull/332 was merged, closing for now
