### ISSUE TITLE
We are at graph v6.0

### ISSUE THREAD

**Issue by Henrik41** [simi/omniauth-facebook#338]
I am not getting the User email despite setting the scope and info_fields.
This gem refers to v4.0 but we are at v6.0
Is this gem still working for v6.0?

**Comment by simi** [comment]
This gems is at v6.0 which points to FB API v3.0 by default. You can use v6.0 FB API is needed by following README.md - https://github.com/simi/omniauth-facebook#api-version.

**Comment by Henrik41** [comment]
great it works! thx
