### ISSUE TITLE
The Facebook Graph API needs to be upgraded by 28 July

### ISSUE THREAD

**Issue by madeleinel** [simi/omniauth-facebook#339]
The current Facebook Graph API version (v3.0) is only available until July 28, 2020.

`omniauth-facebook` should be updated to use Facebook Graph API to 3.1 or above instead.

Thanks!

----

Version 3.1
Released July 26, 2018 | Available until October 27, 2020

https://developers.facebook.com/docs/graph-api/changelog/version3.1

**Comment by simi** [comment]
Thanks for noticing this @madeleinel. You can still use newer version https://github.com/simi/omniauth-facebook#api-version. Anyway I think we can bump major version of this gem and update to FB API v4.0 by default. WDYT?

**Comment by madeleinel** [comment]
That sounds like a good plan to me 🚀  Thanks @simi!

**Comment by simi** [comment]
Would you mind to prepare pull request for this change @madeleinel? I think you can just follow https://github.com/simi/omniauth-facebook/commit/445d6d6872742eda4d5213d000f0f11d97a5c4e2. Just instead of 2.11 use 3.0 and instead of 3.0 you can use 4.0. New gem version should be 7.0.0.

**Comment by madeleinel** [comment]
I tried that before I opened the issue, but I didn't have permission to push to the repo. Is there anything I need to do or set up to get push access @simi?

**Comment by simi** [comment]
@madeleinel you need to fork this reporistory, clone locally, create new branch, commit your changes, push and open pull request

https://opensource.com/article/19/7/create-pull-request-github

Feel free to ping me if you need any additional help.

**Comment by madeleinel** [comment]
Ah, I'd forgotten about the forking step - thanks!

I've opened a PR for this: #341

**Comment by olleolleolle** [comment]
@madeleinel Thanks for reporting and repairing this issue! 🎉

**Comment by simi** [comment]
merged and release, closing

**Comment by juanibiapina** [comment]
It looks like this is a major version bump without breaking changes for users of this library. Is my understand here correct?

The diff doesn't show any changes in the public API of this gem.

**Comment by simi** [comment]
Yes, we do major bumps as well when changing default endpoint (default FB API version).
