### ISSUE TITLE
How do you run unit tests locally?

### ISSUE THREAD

**Issue by dcangulo** [simi/omniauth-facebook#340]
I have forked this open PR https://github.com/simi/omniauth-facebook/pull/315 into my organization account (https://github.com/drophive/omniauth-facebook) and rebased it on the master of this repository to update it from v5 to v6.

I am planning to rebase it whenever something is merged in the master of this repository until you merge the PR into the master of this repository as we really need the feature in that PR and also while keeping our gems updated.

So far it doesn't have any problems in my use case. But I just thought maybe something broke while I am fixing merge conflicts. I am just wondering if I can run unit tests locally?

**Comment by simi** [comment]
1. clone
2. bundle install
3. bundle exec rake test

**Comment by simi** [comment]
#315 awaits more community testing. Feel free to report your results in original case. We can probably merge it.
