### ISSUE TITLE
user profile image url issue from the new graph API requirement

### ISSUE THREAD

**Issue by anklos** [simi/omniauth-facebook#343]
Currently if I turn on facebook development mode, I find that all users' facebook profile image urls will redirect to the default empty facebook image. 

Image urls that saved in my database are like: `http://graph.facebook.com/v4.0/10207720064671302/picture`. And it will redirect to an empty image url like `https://scontent.fsyd3-1.fna.fbcdn.net/v/t1.30497-1/cp0/c15.0.50.50a/p50x50/84628273_176159830277856_972693363922829312_n.jpg?_nc_cat=1&_nc_sid=12b3be&_nc_ohc=hEY_R-t_S40AX_3EtD7&_nc_ht=scontent.fsyd3-1.fna&_nc_tp=27&oh=44a6979759bc9e99b6a97d97e3fe07a7&oe=5F910A38`

I think it relates to the new API change that facebook going to release soon https://developers.facebook.com/docs/graph-api/reference/user/picture/

My question is, shall I set some params in this gem to give me full user image urls that won't redirect, or I should add access token on frontend to query the currently generated profile urls.

Thanks.

**Comment by knu** [comment]
Are the new URLs with access_token added really fetchable?  We keep getting 500 Internal Server Error.

**Comment by knu** [comment]
After upgrading this gem to 8.0.0, we have never succeeded in fetching images.  Image URLs with access_token added do not seem to work at all.

```console
% wget "http://graph.facebook.com/v5.0/xxxxxx/picture?access_token=yyyyyy&type=large"
--2020-11-02 16:47:48--  http://graph.facebook.com/v5.0/xxxxxx/picture?access_token=yyyyyy&type=large
Resolving graph.facebook.com (graph.facebook.com)... 31.13.82.1
Connecting to graph.facebook.com (graph.facebook.com)|31.13.82.1|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-11-02 16:47:48 ERROR 500: Internal Server Error.

% curl -fsSLO "http://graph.facebook.com/v5.0/xxxxxx/picture?access_token=yyyyyy&type=large"
curl: (22) The requested URL returned error: 500 Internal Server Error

% irb
>> open("http://graph.facebook.com/v5.0/xxxxxx/picture?access_token=yyyyyy&type=large").read
Traceback (most recent call last):
        1: from (irb):7
OpenURI::HTTPError (500 Internal Server Error)
```

Removing the access_token parameter, it becomes accessible, at least for now.

You can view the image on a Facebook authenticated browser, though.

**Comment by simi** [comment]
@knu can you try with https as suggested per https://github.com/simi/omniauth-facebook/issues/345?

**Comment by knu** [comment]
@simi Ah, thanks, didn't notice there was already a PR for this.  Will give it a try.

**Comment by pdfrod** [comment]
@simi I tested https://github.com/simi/omniauth-facebook/pull/346 and it fixed the issue for me. Any estimate when it will be merged?

**Comment by simi** [comment]
@pdfod there's no need to wait for that change, since it just change default configuration. You can configure it today per https://github.com/simi/omniauth-facebook#configuring in current version.

Anyway no idea about the merge for now.

**Comment by pdfrod** [comment]
Ah right, I missed that. I guess I don't need to wait for a release, then.

Thanks for the tip!
