### ISSUE TITLE
Change default of secure_image_url to true, because downloading image via http results in 500 error

### ISSUE THREAD

**Issue by swiknaba** [simi/omniauth-facebook#345]
When trying to download the profile image via

```ruby
require 'open-uri'

io = open(request.env['omniauth.auth'].info.image)
```

Facebook responds with a 500 error. Switching protocol from `http` to `https` solves the problem.

Looking into the Facebook docs: https://developers.facebook.com/docs/facebook-login/security#surfacearea
we see that starting from the 6th of October 2018, using HTTPS is mandatory:

> Use HTTPS
>
> Use HTTPS, instead of HTTP, as an internet protocol, because it uses encryption. HTTPS keeps transmitted data private and guards against eavesdropping attacks. It also prevents data from being tampered with during transmission by, for example, introducing advertisements or malicious code.
> 
> On October 6, 2018, all apps will be required to use HTTPS.
>

hence I propose to switch the default of `secure_image_url` from `false` to `true`.

I can open a PR if you agree with the change.

**Comment by simi** [comment]
yes, feel free to do
