### ISSUE TITLE
image_url results in `API calls from the server require an appsecret_proof argument` error

### ISSUE THREAD

**Issue by prognostikos** [simi/omniauth-facebook#347]
We just upgraded to version 8.0.0 which added the `access_token` parameter to the image url. Now we're getting an error when trying to download an image:

```
{
   "error": {
      "message": "API calls from the server require an appsecret_proof argument",
      "type": "GraphMethodException",
      "code": 100,
      "fbtrace_id": "REDACTED"
   }
}
```

It looks to me like the image url also needs to include the `appsecret_proof` parameter as well. Would a PR to add this be accepted?

**Comment by simi** [comment]
@anklos @olivierjm @tupakapoor any idea? Isn't that related to some app specific setting?

**Comment by tupakapoor** [comment]
I’m not certain - I don’t recall seeing that in the docs nor did I receive that issue when pulling a profile picture. Will dig a little today and see if I can find anything/reproduce.

**Comment by simi** [comment]
@prognostikos is your problem gone when providing `appsecret_proof`?

**Comment by OlivierJM** [comment]
> @anklos @OlivierJM @tupakapoor any idea? Isn't that related to some app specific setting?

We also upgraded to v8.0 and it works fine with the access_token, The case might for `appsecret_proof ` might be specific for some apps. @tupakapoor let us know what you find.

**Comment by anklos** [comment]
@prognostikos can you please check if you have this setting turned on 

![image](https://user-images.githubusercontent.com/530145/96931560-3996b880-1509-11eb-8ae2-f10f57918213.png)

**Comment by prognostikos** [comment]
> @prognostikos is your problem gone when providing `appsecret_proof`?

Yes, it works if I include `appsecret_proof` in the image url.

**Comment by prognostikos** [comment]
> @prognostikos can you please check if you have this setting turned on

We do have this setting on. So I guess this should be a configuration option if you folks want to include it. Let me know and I'll submit a PR.

**Comment by jamesbebbington** [comment]
Hey @prognostikos we also have the `appsecret_proof` option turned on, so would be very grateful to see a PR for support for it submitted.
