### ISSUE TITLE
Issue with access_tokens expiring for photos?

### ISSUE THREAD

**Issue by cmccarty** [simi/omniauth-facebook#360]
Is it possible that PR #344 added access_tokens to all types of scoped requests?

I am seeing cases where FB returns `Error validating access token`, but if I remove `access_token` from the URL completely, then the URL works.

```
{
  "error": {
    "message": "Error validating access token: The user has not authorized application 1698300210405782.",
    "type": "OAuthException",
    "code": 190,
    "error_subcode": 458,
    "fbtrace_id": "AbR6lWzzqYH1RoWbOtIJbbK"
  }
}
```

From the FB docs https://developers.facebook.com/docs/graph-api/reference/user/picture/#requirements
it seems that an access_token is not needed for /picture requests for app-scoped user_ids. Does the current code account for this context?

Anyone else seeing similar issues? Or is it just me?

**Comment by swiknaba** [comment]
from https://developers.facebook.com/docs/graph-api/reference/user/picture/#requirements
```
If querying an App-Scoped User ID:

None
If querying a User ID:

User or Page access token for Facebook Login authenticated requests
App access token for server-side requests
Client access token for mobile or web client-side requests
```

and from https://developers.facebook.com/docs/messenger-platform/identity/id-matching/ we learn:

> When a person uses Facebook Login on a website or a mobile app, an ID is created for the specific Facebook app, which is called app-scoped ID

From this I understand, that we are in the first case _If querying an App-Scoped User ID_, thus an access token might indeed not be necessary.
