### ISSUE TITLE
You are using an old OmniAuth version

### ISSUE THREAD

**Issue by arslanyousaf77** [simi/omniauth-facebook#363]
I have installed the gem using `gem 'omniauth-facebook'`. When I run the server it gives the error `You are using an old OmniAuth version, please ensure you have 1.0.0.pr2 version or later installed. (RuntimeError)`. Can anyone please help?

**Comment by swiknaba** [comment]
That has nothing to do with this gem in particular. Check out the gemspec file to see dependencies, go to the omniauth gem and see the latest major version jump (which had quite some implications on how you use these gems!), then check your own app and see where you got this old version from...

This question + answer should be on stackoverflow, as this looks like a general problem with installing multiple gems with shared dependencies but different version constraints. You should also read this changelog: https://github.com/omniauth/omniauth/releases/tag/v2.0.0
