### ISSUE TITLE
Incorrect github release version

### ISSUE THREAD

**Issue by sbocinec** [simi/omniauth-facebook#370]
The GitHub release version metadata for `v9.0.0` git tag seems to be wrong - instead of `9.0.0` it displays the latest version is `7.0.0` with the following title: `v7.0.0 (defaults to FB Graph API 5.0) Latest`, as can be seen on the screenshots:

* ![Screenshot from 2021-11-23 17-07-02](https://user-images.githubusercontent.com/4834459/143060689-53f46ad8-0d7a-4167-9a42-4d0730540c34.png)

* ![Screenshot from 2021-11-23 17-07-12](https://user-images.githubusercontent.com/4834459/143060716-b8930bbd-6022-4b1d-96e1-ad2109f4d069.png)

It's just a cosmetic issue, though better to be fixed (if possible) to avoid confusion. 

Thank you for your work!

**Comment by simi** [comment]
@sbocinec thanks for the report :heart:. It was just wrong name of the release. It should be fixed, feel free to check and close the issue.

**Comment by sbocinec** [comment]
@simi everything looks good now. Thanks for the quick fix :handshake:
