### ISSUE TITLE
The action 'facebook' could not be found for Devise::OmniauthCallbacksController

### ISSUE THREAD

**Issue by ndvbd** [simi/omniauth-facebook#373]
I am getting the message

`The action 'facebook' could not be found for Devise::OmniauthCallbacksController`

How can I debug what's going on? Where should I place the breakpoint?

**Comment by swiknaba** [comment]
No offence, but I believe this question belongs to [StackOverflow](https://stackoverflow.com/search?q=debug+Devise%3A%3AOmniauthCallbacksController). Mind closing the issue, unless there is a real issue related to the gem?
