### ISSUE TITLE
Graph API v5.0 has already unavailable.

### ISSUE THREAD

**Issue by ksss** [simi/omniauth-facebook#374]
https://developers.facebook.com/docs/graph-api/changelog/version5.0

> Released Oct 29, 2019 | Available until Feb 3, 2022

Are there any plans to upgrade Graph API?

ref: https://github.com/simi/omniauth-facebook/pull/366

**Comment by simi** [comment]
@ksss would you mind to send PR to update to newer version of API? You can switch to different version as described in README https://github.com/simi/omniauth-facebook#api-version. But it would be nice to keep available version as a default.

**Comment by ksss** [comment]
That's a good option.
Thank you.
