### ISSUE TITLE
 first_name blank

### ISSUE THREAD

**Issue by dcalixto** [simi/omniauth-facebook#384]
Hello i'm trying to get the facebook first name to put on username on omniauth-facebook gem

but just get the name, looking at facebook docs indeed has first_name but how to get it?

here is the code

      def self.from_omniauth(access_token)
        data = access_token.info
        user = User.where(email: data['email']).first
        user ||= User.create(name: data['name'],
                             email: data['email'],
                             username: data['first_name'],
                             avatar_url: data['image'],
                             provider: access_token['provider'],
                             uid: access_token['uid'],
                             password: Devise.friendly_token[0, 20])
    
        user
      end

i tried the info_fields but did not worked

      config.omniauth :facebook, '', '', scope: 'email', info_fields: 'first_name'

so someone can help?

**Comment by dcalixto** [comment]
ok, fixed, just forget to restart the server!

**Comment by u296539883** [comment]
![2D884847-98F8-476F-BDCA-9E2309CDA566](https://github.com/simi/omniauth-facebook/assets/132947308/c2dada6b-23c0-4431-845b-ddd5b6f995ed)
