### ISSUE TITLE
Facebook not always returning email for user?

### ISSUE THREAD

**Issue by swrobel** [simi/omniauth-facebook#61]
I've looked all over the Facebook docs and can't seem to figure out why, even if I require the email permission, I still sometimes get users who are authorized, but do not have email included in the extra hash. Does anyone have any clue how this is possible and how I can absolutely require an email from Facebook?

**Comment by zeitnot** [comment]
The reason is simple. I have  a facebook account for test purposes only. The e-mail related to this fb account was not confirmed. So when I was trying to login via facebook the email field was coming  as nil. After confirmed that e-mail, facebook started to send the e-mail. The main reason is about unconfirmed e-mail address.

**Comment by toobulkeh** [comment]
That's ONE reason, but not the only reason.

**Comment by lsandeep83** [comment]
This can also happen if the user has signed up using his phone number.

**Comment by geoffreymm** [comment]
As @TeamRainless said and confirmed by the Facebook developers page:
> Note, even if you request the email permission it is not guaranteed you will get an email address. For example, if someone signed up for Facebook with a phone number instead of an email address, the email field may be empty.

[From here](https://developers.facebook.com/docs/facebook-login/permissions/v2.2#reference-email)

Maybe this can be the reason for the %1 or 2% emails not returned.

**Comment by TeamRainless** [comment]
This is correct.

I still get about a 5% failure rate with Omiauth-Facebook.  I have a site
where people vote for things, so it could easily be that some of them are
just signing up for unverified accounts. (Which would account for my higher
average of no emails).

All I did was create a hook that redirects to an edit page where it
requests the email address and anything else that is missing.

The next step would be to have them confirm unconfirmed addresses (you can
assume that missing Facebook emails are unconfirmed). But that's something
Devise can easily handle.

**Comment by renztoygwapo** [comment]
still not fixed!
returning an empty email

**Comment by TeamRainless** [comment]
Of course it's still returning an empty email.  Didn't you read any of
these messages? Sometimes it just does that. You have to make a hook where,
if it doesn't return an email, the user is required to type one. I even
posted my own solution somewhere in this rail.

-DH

**Comment by brentmulligan** [comment]
@renztoygwapo If you recently created the FB App and are on FB API v2.4.2 you need to also include info_fields along with scope at config, otherwise email is not included in the omniauth.auth hash. It looks like this has been fixed in the master branch here but doesn't seem to be available on ruby gems yet.

``` ruby
config.omniauth :facebook, secrets.fb_app_id, secrets.fb_app_secret,
                scope: 'public_profile,email', info_fields: 'email,name'
```

**Comment by simi** [comment]
@brennanpayne @renztoygwapo this change will be released this week (I'll be back on tuesday), but I'm not sure how to handle versioning for this. @mkdynamic any idea?

**Comment by victorrodrigues** [comment]
Thanks @brentmulligan!

**Comment by ajahongir** [comment]
have same issue

**Comment by frankjwu** [comment]
+1, thanks @brentmulligan!

**Comment by jentuva** [comment]
I get empty email , verified, first_name , last_name ... etc
all I get are the id,displayName,photo_url
I use public_profile,email scope even that public_profile is sent by default 
what is the cause ?? O.o

**Comment by vaihtovirta** [comment]
thanks for advice, @brentmulligan!
I had the same issue with recently created fb app.

**Comment by 3zcurdia** [comment]
I try the fix suggested by @brentmulligan and It didn't work I still having empty email response and also I am using FB API 2.4

**Comment by vaihtovirta** [comment]
@3zcurdia Did you try to use version from master branch?

**Comment by 3zcurdia** [comment]
Nope, but I tryed and it worked thanks

**Comment by ajahongir** [comment]
I also had a problem with getting an en amail, after couple hours It worked )). very strange.

**Comment by thalesfp** [comment]
@brentmulligan works here. Thank you!

**Comment by nimitzshah** [comment]
Thanks @brentmulligan!

**Comment by shahidaali** [comment]
Now facebook returns only id and name fields in user info by default, if you need other fields, you have to define these fields in your request.
e.g $fb->get('/me?locale=en_US&fields=name,email,first_name,last_name');

**Comment by cborchert** [comment]
Thanks, @shahidaali . That solved this issue for me.

**Comment by shahidaali** [comment]
Facebook will not return the email for those users whose email is pending for confirmation, when a user creates new account on facebook a confirmation email is sent to the user, but if user did't confirm his email, facebook will not return his email in user info even you added email permission in scope, until user confirms his email.

**Comment by Altiano** [comment]
@shahidaali thanks man, it solve the problem. do you know where can i found a up to date facebook sdk for php tutorial? I think the problem with most of the people is we're watching/reading old tutor on youtube or any other source so sometime the code is not valid anymore..

**Comment by shahidaali** [comment]
@Altiano Thanks buddy, you can get latest news and updates on facebook developers blog at https://developers.facebook.com/blog/

**Comment by dannypule** [comment]
If you're using the Javascript SDK you can define these fields and get the email and picture using the '/me' parameter like this:

          '/me?fields=first_name, last_name, picture, email'

Full function would be:

           FB.api('/me?fields=first_name, last_name, picture, email', function(response) {
              console.log(response);
              document.getElementById('status').innerHTML =
                'Thanks for logging in, ' + response.name + '!';
            });

**Comment by aanjna** [comment]
User email not written/fetch with this code of auth

if ( isset( $session ) ) {
  // graph api request for user data
  $request = new FacebookRequest( $session, 'GET', '/me' );
  $response = $request->execute();
  // get response
  $graphObject = $response->getGraphObject();
     	$fbid = $graphObject->getProperty('id');              // To Get Facebook ID
 	$fbfullname = $graphObject->getProperty('name'); // To Get Facebook full name
	$femail = $graphObject->getProperty('email');    // To Get Facebook email ID

	/* ---- Session Variables -----*/
	$_SESSION['FBID'] = $fbid;           
        $_SESSION['FULLNAME'] = $fbfullname;
	$_SESSION['EMAIL'] =  $femail;
    /* ---- header location after session ----*/
checkuser($fbid,$fbfullname,$femail);

**Comment by mateuszgwozdz** [comment]
If you are using facebook SDK 2.4 or higher you need to add "fields" in the strategy 

`FacebookStrategy.php 
line 131
BEFORE
$me = $this->serverGet('https://graph.facebook.com/me', array('access_token' => $access_token), null, $headers);
AFTER:
$me = $this->serverGet('https://graph.facebook.com/me', array('access_token' => $access_token,'fields'=>'email,name,first_name,last_name,age_range,gender'), null, $headers);
`

Regardless of the field list, if you want to get more information that is not by default provided by Facbeook, the permissions need to be in the "scope" array. 

!Facebook needs to approve your request for additional permissions

Default data provided by SDK includes: email, public profile, user_friends

**Comment by aanjna** [comment]
Hi
here I didn't received FacebookStrategy.php file in my src/Facebook SDK files 
the code creates problem by trying the given options too please have a look
on my fbconfig.php file to retrive user's fb data

<?php
session_start();
// added in v4.0.0
require_once 'autoload.php';
require_once 'functions.php'; 
use Facebook\FacebookSession;
use Facebook\FacebookRedirectLoginHelper;
use Facebook\FacebookRequest;
use Facebook\FacebookResponse;
use Facebook\FacebookSDKException;
use Facebook\FacebookRequestException;
use Facebook\FacebookAuthorizationException;
use Facebook\GraphObject;
use Facebook\Entities\AccessToken;
use Facebook\HttpClients\FacebookCurlHttpClient;
use Facebook\HttpClients\FacebookHttpable;
// init app with app id and secret

FacebookSession::setDefaultApplication( 'app-id','app-secrat' );
// login helper with redirect_uri
    $helper = new FacebookRedirectLoginHelper('http://www.myweb.in/1353/fbconfig.php' );
try {
  $session = $helper->getSessionFromRedirect();
} catch( FacebookRequestException $ex ) {
  // When Facebook returns an error
} catch( Exception $ex ) {
  // When validation fails or other local issues
}
// see if we have a session
if ( isset( $session ) ) {
  // graph api request for user data
  $request = new FacebookRequest( $session, 'GET', '/me?field= email, name, id' );
  $response = $request->execute();
  // get response
  $graphObject = $response->getGraphObject();
     	$fbid = $graphObject->getProperty('id');              // To Get Facebook ID
 	    $fbfullname = $graphObject->getProperty('name'); // To Get Facebook full name
	    $femail = $graphObject->getProperty('email');    // To Get Facebook email ID

	/* ---- Session Variables -----*/
	    $_SESSION['FBID'] = $fbid;           
            $_SESSION['FULLNAME'] = $fbfullname;
	    $_SESSION['EMAIL'] =  $femail;
    /* ---- header location after session ----*/
checkuser($fbid,$fbfullname,$femail);
  header("Location: index.php");
} else {
  $loginUrl = $helper->getLoginUrl(array('scope' => 'email'));
 header("Location: ".$loginUrl);
}
?>

**Comment by woodcrust** [comment]
Very, very big thanks @brentmulligan!

**Comment by starthereau** [comment]
Thanks @dannypule just what I needed!

**Comment by realmensah** [comment]
Figured this out. For omniauth-facebook, you need to add the scope on fb login response. Change in facebook.js.coffee:

$('#sign_in').click (e) ->
e.preventDefault()
FB.login (response) ->
window.location = '/auth/facebook/callback' if response.authResponse

To:

$('#sign_in').click (e) ->
e.preventDefault()
FB.login ((response) ->
window.location = '/auth/facebook/callback' if response.authResponse), scope: "email"

**Comment by diegodurante** [comment]
If you are using ruby on rails and the omniauth-facebook gem, remember to update that gem to the last 3.0.0 version.

**Comment by WhiteWolves** [comment]
SOLUCION

Bien estube experimentando con la Graph API de facebook y el que no regrese el email del usuario se debe a que nunca confirmo ese correo electronico, por lo tando facebook no lo devuelve como informaciom valida.

ya quedaria a las necesidades de cada quien si se permite registrar al usuario sin estar precente el email. O pedirle al usuario que ingrese un email manualmente.

**Comment by Shannanigans** [comment]
Facebook users can register using a phone number instead of an email addy. This means that facebook does not have an email address for that user.

https://developers.facebook.com/docs/facebook-login/permissions#reference-email

**Comment by dlynam** [comment]
I recently experienced this issue with the latest omniauth-facebook 3.0.0 version.

**Comment by lucianoinso** [comment]
@shahidaali thank you so much! This solved the problem. It's freaking  unbelievable that this doesn't appear on Facebook's permissions documentation.

**Comment by shahidaali** [comment]
@lucianoinso you are welcome...!

**Comment by aanjna** [comment]
okk done EOC

**Comment by ndeokar** [comment]
we could add email check on the returned data. then prompt user with dialog for adding email. its just work around.

**Comment by dsp1589** [comment]
Am experiencing this issue right now :( In android fb sdk **facebook-android-sdk:[4,5)** I tried almost all the solution provided here and am using my own personal account for testing. [Email id is verified and no phone no provided to FB]. If any one know the fix, please help. its driving me crazy.

            Bundle parameters = new Bundle();
            parameters.putString("fields",
                    "id,first_name,email,gender,birthday,name");
            parameters.putString("info_fields","email,name");
            request.setParameters(parameters);

**Comment by TeamRainless** [comment]
I can't believe this is still getting messages... I gave up on this a LONG
time ago and just created a workaround that asks the user to supply an
email if Facebook doesn't. (You'll find my solution probably like 75
messages back...)

**Comment by simi** [comment]
@TeamRainless I have no idea what's still discussed here. You're not getting email from FB everytime (depends on user settings) and you need to ask him for email if you need it and response is missing that.

**Comment by TeamRainless** [comment]
That's... exactly what I just said. :p

I was just responding to... I don't know... I guess the 75th email that I'm
attached to. (I don't know how exactly I got into the github chain...)

**Comment by ljnet** [comment]
+1, localhost ok, online fail.
have to ask user to input email.

**Comment by ndeokar** [comment]
@dsp1589  : have a look at [this](http://androidhiker.blogspot.in/2016/08/facebook-email-not-found-via-graph-api.html).

**Comment by Mycroft1891** [comment]
I'm using the callback process and I noticed also that a lot of users that try to create an account fail to do so because we need the user's email address.

**Comment by HariGJ** [comment]
facebook integration in ios.
i'm using the following code.

  [[[FBSDKGraphRequest alloc] initWithGraphPath:@"me" parameters:@{@"fields" : @"email, name"}]

Please help me.
Thanks.

**Comment by inicsmith** [comment]
I ran into this using https://github.com/ueberauth/ueberauth_facebook in an Elixir / Phoenix project and fixed it by adding profile_fields: "email" to my config.  When I didn't add profile fields I would sometimes receive a nil email. 

config :ueberauth, Ueberauth,
  providers: [
    facebook: {Ueberauth.Strategy.Facebook, [default_scope: "email,public_profile", profile_fields: "email"]}
  ]

**Comment by riston** [comment]
@inicsmith well the user could remove the email request when the permission window is shown. It's common problem to avoid breaking the auth flow, it's always possible to ask email from user and verify it.

**Comment by ahmedawad250** [comment]
You should add email to scope or add to facebook api get data
api('/me?fields=name,email')

**Comment by WarrEagle** [comment]
^ That is not helpful. If a user has their settings set to not supply their email you will get either a null address or an address like 34132142412342@facebook.com if they have messenger enabled. 

You just have to detect and/or drop the missing address or @facebook.com address, then force the user to supply a valid email if you require it.

**Comment by AmaliDeveloper** [comment]
You can get the solution here Facebook SDK connect [Link](https://youtu.be/xKC5pFEpH2A)

**Comment by dfloresgonz** [comment]
@TeamRainless is right!!! if the user has its phone number set email is not returned I have tested with two accounts one with the phone set and the other one is not, the first one doesn't retrieve the email but the 2nd account does. I guess there is nothing else to do right?

**Comment by aanjna** [comment]
Case closed
!!!

Thanks with regards,

Praveen Patel
https://in.linkedin.com/in/praveenkaanjna
Mo-09660294530

**Comment by steedems** [comment]
I had two identical Facebook apps: one was returning the email and the other was not (same user).

after 3 beers i started trying random stuff, and this one did the trick 
<img width="797" alt="screen shot 2017-04-12 at 17 38 10" src="https://cloud.githubusercontent.com/assets/7896422/24966531/7b82ed64-1fa7-11e7-8faf-3965696d7f49.png">

**reset Client Token**

@dfloresgonz hope it helps

**Comment by jaiswarvipin** [comment]
One of the my friend was trying to the issue from last 5 days. huummm very irritating. which got love in 2 min...

**Assumption:** using PHP for O2Authentication
**Solution:**

`    $loginURL =  $fb->getLoginUrl({your redirect URL},['email']);`

And job is done.

Thanks & Regards
Jaiswar Vipin Kumar R.

**Comment by RicardoRamirezR** [comment]
That worked for me @shahidaali Thank you so much!

**Comment by goyalabhishek585** [comment]
Hi My name is "Goyal Abhishek" I was married for 9years with Keshika and we had a kid together. Things started getting ugly and we had fights and arguments almost every time... it got worse at a point that she filed for divorce... I tried my best to make her change her mind & stay with me. She moved out of the house and still went ahead to file for divorce... I pleaded and tried everything but still nothing worked. The breakthrough came when my friend introduced me to this wonderful, great spell caster  who has helped him and his wife solve their infertility problem... I have never been a fan of things like this but just decided to try reluctantly cause I was desperate and left with no choice... He did special prayers for me... Within 2 days she called me and was sorry for all the emotional trauma she had cost me, she moved back to the house and we continue to live happily. what a wonderful miracle Dr. Ken did for me and my family. I have introduced him to a lot of couples with problems across the world and they have had good news... I strongly believe someone out there need's his help (supersolutionhome1@gmail.com or supersolutionhom@yahoo.com)so make extra effort to save your marriage/relationship if it's truly worth it. call him +2348074433380 His website: supersolutionhome.webs.com

**Comment by goyalabhishek585** [comment]
Hi My name is "Goyal Abhishek" I was married for 9years with Keshika and we had a kid together. Things started getting ugly and we had fights and arguments almost every time... it got worse at a point that she filed for divorce... I tried my best to make her change her mind & stay with me. She moved out of the house and still went ahead to file for divorce... I pleaded and tried everything but still nothing worked. The breakthrough came when my friend introduced me to this wonderful, great spell caster  who has helped him and his wife solve their infertility problem... I have never been a fan of things like this but just decided to try reluctantly cause I was desperate and left with no choice... He did special prayers for me... Within 2 days she called me and was sorry for all the emotional trauma she had cost me, she moved back to the house and we continue to live happily. what a wonderful miracle Dr. Ken did for me and my family. I have introduced him to a lot of couples with problems across the world and they have had good news... I strongly believe someone out there need's his help (supersolutionhome1@gmail.com or supersolutionhom@yahoo.com)so make extra effort to save your marriage/relationship if it's truly worth it. call him +2348074433380 His website: supersolutionhome.webs.com

**Comment by rasool182716** [comment]
Still am also facing this issue... Please let me know if anyone know to how to fix it...

**Comment by cozzbie** [comment]
Ran into this and the only thing that worked was requesting for permitted fields through the API`FB.api("me", {fields: "email,..."}, callback)`

**Comment by YeWin** [comment]
@shahidaali Thank you so much!
That worded for me even with old PHP file_get_contents() method.

workaround: `file_get_contents('https://graph.facebook.com/me?locale=en_US&fields=name,email,first_name,last_name&access_token=' . $access_token['access_token']);`

**Comment by statico** [comment]
FWIW, I was trying to debug something similar and found that I was sending the `scope` parameter at the wrong time: https://github.com/jaredhanson/passport-facebook/issues/214#issuecomment-348659884

**Comment by joaovictorpsantos** [comment]
Today I was running some tests and I came across the same situation, the user's email was not being returned.

Then I realized that Facebook has an option that allows the user to "hide" his or her email, leaving it private, and when the user does it, it is not possible to get the email.

**Comment by TeamRainless** [comment]
It's VERY simple: Just create a catch so that, if the email is not
returned, the user must manually input it.

**Comment by nandotuc17** [comment]
Se o email vier nulo basta usar o id_do_usuario@facebook.com já ajuda em algo pelo menos.

**Comment by nandotuc17** [comment]
Também percebi que se eu solicitasse o perfil publico + email via string array no xml não funcionava, vinha apenas o perfil publico, como o perfil publico já vem por padrao eu retirei as permissões do xml e inseri diretamente no código da classe java só o email.

LoginManager.getInstance().logInWithReadPermissions(MainActivity.this,Arrays.asList("**email**"));

**Comment by RevealedFrom** [comment]
@steedems  No joy for me. I have the same situation, two identical apps, one returns email but one won't.

**Comment by simi** [comment]
@RevealedFrom for the same user asking for the same permissions?

**Comment by RevealedFrom** [comment]
@simi Yes, testing with the same Facebook user account. Exact same Express app with passport-facebook, and just switching client id and client secrets to test with different Facebook apps.  So far, the score is 2 will return emails, and 1 will not.

**Comment by simi** [comment]
Are there any differences between facebook apps configurations?

**Comment by RevealedFrom** [comment]
Went through page by page, couldn't find any material differences.  Anyway, it says email is always approved by default. I wonder what other settings could have prevented email from being sent.

From the user side, going to [www.facebook.com/settings?tab=applications](url) shows that two apps have the choice of email but one doesn't.

**Comment by samarulrajt** [comment]
For me this code worked charm to fetch user info and email.
` FB.api('/me?fields=name,email,first_name,last_name,id', function(response) {
   console.log(response);
 }, {scope: 'public_profile,email'});
`

**Comment by feliperaul** [comment]
I'm know clocking at around 6 hours of debugging, without any luck. Before e-mail was being retrieved, now it isn't. Created test users on Application Dashboard, and nothing. Created a new app for testing only, nothing. The info hash comes with name and image only, no matter what I pass on scope and info_fields. 

This is the latest code I'm running, but I've tried more then 50 variations of all these parameters. Giving up for the week. 

```
Rails.application.config.middleware.use OmniAuth::Builder do

  provider(:facebook,
    Rails.application.secrets.facebook_app_id,
    Rails.application.secrets.facebook_app_secret,
    scope: 'email,public_profile',
    info_fields: 'name,email',
    display: 'popup',
    callback_path: "/tourists/auth/facebook/callback",
    token_params: { parse: :json },
    client_options: { site: "https://graph.facebook.com/v3.0", authorize_url: "https://www.facebook.com/v3.0/dialog/oauth" }
  )

end
```

**Comment by feliperaul** [comment]
@shahidaali could you please take a look?

**Comment by feliperaul** [comment]
My current workaround - terrible, but only way I managed to get an e-mail addres - was using Koala gem, initializing an instance with the `request.env['omniauth.auth'].credentials.token` token  and then requesting the e-mail address using the token:

`@graph = Koala::Facebook::API.new(request.env['omniauth.auth'].credentials.token)
`profile = @graph.get_object("me", fields: ['email'])`

**Comment by codevanaco** [comment]
After over-reading all comments and becoming increasingly frustrated, I found a quick solution:


`passport.use(new FacebookStrategy({
        clientID: '18814......',
        clientSecret: 'c27cccd.....',
        callbackURL: 'https://localhost:1443/auth/facebook/callback'
    },
    function(accessToken, refreshToken, profile, done) {
        return done(null, {
            token: accessToken,
            profile: profile
        });
    }));

app.get('/auth/facebook/callback',
    passport.authenticate('facebook'),
    function(req, res) {

        let id = req.user.profile.id;
        let token = req.user.token;


        /* retrieves user image & email */
        request('https://graph.facebook.com/v3.1/me?fields=id%2Cname%2C%20email%2C%20picture&access_token=' + token, function(error, response, body) {

            if (error) return res.send(400);

            const data = JSON.parse(body);

            let picture = data.picture;
            let email = data.email;

            res.send({
                status: 200,
                body: {
                    token: req.user.token,
                    profile: req.user.profile,
                    image: picture,
                    email: email
                }
            });


        });


    }

);
app.get('/rest/facebook',
    passport.authenticate('facebook', {
        scope: ['email']
    }),
    function(req, res) {
        console.log(req)
        res.send(200);
    }
);`

**Comment by sushant12** [comment]
thanks @codevanaco , adding it to the scopes did the trick

**Comment by gsolak** [comment]
> https://graph.facebook.com/me?fields=email,first_name,last_name&access_token={token}

By default, the email field will not return unless specified.
