### ISSUE TITLE
Issue with omniauth-facebook

### ISSUE THREAD

**Issue by raybesiga** [simi/omniauth-facebook#64]
Using omniauth-facebook in my Rails app raises this issue. How do I fix this?
{
   "error": {
      "message": "Missing client_id parameter.",
      "type": "OAuthException",
      "code": 101
   }
}

**Comment by Luna2442** [comment]
I'm not getting this to work. With ENV I get the error above BUT I do get signed in. Without ENV, I get taken to a page from FB that reads:

Sorry, something went wrong.
We're working on getting this fixed as soon as we can.

But I don't get signed in. What am i doing here??
