### ISSUE TITLE
'Could not authorize you from Facebook because "Csrf detected".'

### ISSUE THREAD

**Issue by tomsoderlund** [simi/omniauth-facebook#73]
Seems like v1.4.1 introduced an issue with CSRF:

http://stackoverflow.com/questions/11548539/rails-3-2-facebook-auth-csrf-failure
http://stackoverflow.com/questions/11597130/omniauth-facebook-keeps-reporting-invalid-credentials

**Comment by AlvaroOlivencia** [comment]
Upgrading to omniauth-facebook 2.0.0 fixed the issue for me (using FB JS SDK).
From the changelog: **fix CSRF exception when using FB JS SDK and parsing signed request (765ed9, @mkdynamic)**

**Comment by simi** [comment]
Thanks for info @AlvaroOlivencia!

**Comment by hecbuma** [comment]
For me was HTTP Auth the issue, I just get rid of it  and that was all

**Comment by BenV** [comment]
We ran into this issue after turning on encrypted cookies in Rails. Turns out we were making a simultaneous request when starting the auth flow which was overwriting the omniauth state. This didn't happen before encrypted cookies because they were only sent when changed. This post sums the issue up nicely: http://techbrahmana.blogspot.com/2013/10/invalid-credentails-omniauth-oauth2.html

**Comment by olegprin** [comment]
gg

**Comment by olegprin** [comment]
1) sudo apt-get install libwww-csrf-perl

2)  added this to our config/initializers/omniauth.rb:
Rails.application.config.middleware.use OmniAuth::Builder do
     provider :facebook, 162491*************, "**********************", provider_ignores_state: true
end

**Comment by olegprin** [comment]
1) sudo apt-get install libwww-csrf-perl

2) added this to our config/initializers/omniauth.rb:
Rails.application.config.middleware.use OmniAuth::Builder do
 provider :facebook, 1624915**********, "**********************", {:scope => "email, publish_stream", :client_options => {:ssl => {:ca_path => "/etc/pki/tls/certs", :ca_file => "/etc/pki/tls/cert.pem"}}}
end

**Comment by olegprin** [comment]
1) sudo apt-get install libwww-csrf-perl

2) added this to our config/initializers/omniauth.rb:
Rails.application.config.middleware.use OmniAuth::Builder do
provider :facebook, 1624915*******, "*******************", {:scope => "email, publish_stream", :client_actions => {:ssl => {:ca_path => "/etc/pki/tls/certs", :ca_file => "/etc/pki/tls/cert.pem"}}}
end

**Comment by olegprin** [comment]
1) sudo apt-get install libwww-csrf-perl

2) added this to our config/initializers/omniauth.rb:
Rails.application.config.middleware.use OmniAuth::Builder do
provider :facebook, 1624915****, "****************", provider_ignores_state: true
end

**Comment by hajder** [comment]
@olegprin how many more times will you post this comment?

**Comment by mirzoz** [comment]
@emkman, your method really works! thanks bro!

**Comment by davidalejandroaguilar** [comment]
> True, you wouldn't want to mess with Homakov.
> 
> This is probably not the answer you're looking for but `omniauth-facebook` should work out of the box. If you use it solo (without any other gem) and set it up properly it should work. I'm using it with `devise` at this moment and it's working fine as well.
> 
> However, it seems to me like any deviation from the normal `omniauth-facebook` flow seems to trigger CSRF detection. So far, here are some of the things that seem to do it:
> 
> * Defining your app credentials in two different initializers, usually `omniauth.rb` and `devise.rb`. [source](https://github.com/mkdynamic/omniauth-facebook/issues/73#issuecomment-9502746)
> * Having a domain name mismatch between your live site and the site url configured within your OAuth application. [source](https://github.com/mkdynamic/omniauth-facebook/issues/73#issuecomment-12745755)
> * Having a cookie domain that doesn't match the redirect_uri. [source](https://github.com/intridea/omniauth-oauth2/issues/58#issuecomment-49590041)
> * Leaving the facebook application in sandbox mode, so the domain name doesn't match the production one. [source](https://github.com/mkdynamic/omniauth-facebook/issues/73#issuecomment-21964889)
> * Adding a `before_filter :authenticate` to the OmniauthCallbacksController or ApplicationController (since OmniauthCallbacksController inherits from ApplicationController). [source](http://stackoverflow.com/questions/14662454/why-am-i-receiving-this-authorization-code-has-been-used-after-the-first-2-use/16859381#16859381)
> * Using `omniauth-facebook` in conjunction with Facebook's client-side flow. [source](https://github.com/mkdynamic/omniauth-facebook/pull/96#issuecomment-29681731)
> * Messing with the `state` param.

So `omniauth-facebook` is not compatible with Facebook's client-side flow?

**Comment by giandevsecops** [comment]
*SOLUTION that worked for me: clearing computer temps and cache, and clearing the browser. Reopening app. CSFR is a Cross Site Request Forgery. So, in this case, either it is a real attack happening or the site/app OKTA SSO verification system just thinks there is a Csfr going on.  If it is not a Persistent attack, then clearing the cache/temps and browser and reopening might do. if not do that but also restart computer. Ultimately do clear cache but switch browser/app if possible for what is intended. Last but not least, if none of that work give your computer and network a thorough check up, might be actually infected. Of course, you could also just report the issue from beginning but might have to wait. I did the steps I stated here and it work for me without need of escalation.
