### ISSUE TITLE
Facebook redirecting me to /#_=_

### ISSUE THREAD

**Issue by etagwerker** [simi/omniauth-facebook#79]
Somehow things started to fail when I upgraded to 1.4.1, now Facebook is redirecting me to /#_=_ instead of /oauth/facebook/callback

What could be wrong here? 

I've seen threads where it says that it will append #_=_ to the redirect_uri, but for me it's just redirecting me to 

```
/#_=_
```

which is very annoying as it breaks the entire authentication flow. 

Has anyone experienced this? 

Please let me know. Thanks!

**Comment by fabriziobertoglio1987** [comment]
Hello, I am having issues and being redirected on login to #_=_ URL. I commented on the following post and opened a Stackoverflow Question
Thanks
Fabrizio

https://github.com/mkdynamic/omniauth-facebook/issues/220
http://stackoverflow.com/questions/42549803/devise-omniauth-facebook-redirect-uri-isnt-an-absolute-uri
